# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_accepted_insurance_auction_deliveries_auctions_bids_cart_items_diagnoses_doctor_ratings_doctors_orde'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('reserve_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('auction_id', models.AutoField(primary_key=True, serialize=False)),
                ('end_date', models.DateField(auto_now_add=True)),
                ('remedy_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Auction_Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Auction')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.User')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remedy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Remedy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.User')),
            ],
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('insurance_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('repurchase_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Delivery')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('review', models.CharField(max_length=500)),
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Remedy_Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Rating')),
                ('remedy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Remedy')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Doctor',
        ),
        migrations.DeleteModel(
            name='Accepted_Insurance',
        ),
        migrations.DeleteModel(
            name='Auction_deliveries',
        ),
        migrations.DeleteModel(
            name='Auctions',
        ),
        migrations.DeleteModel(
            name='Bids',
        ),
        migrations.DeleteModel(
            name='Cart_items',
        ),
        migrations.DeleteModel(
            name='Diagnoses',
        ),
        migrations.DeleteModel(
            name='Doctor_Ratings',
        ),
        migrations.DeleteModel(
            name='Order_Deliveries',
        ),
        migrations.DeleteModel(
            name='Order_Items',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Remedy_Ratings',
        ),
        migrations.DeleteModel(
            name='Symptoms',
        ),
        migrations.DeleteModel(
            name='Treatments',
        ),
        migrations.RemoveField(
            model_name='payment_information',
            name='id',
        ),
        migrations.RemoveField(
            model_name='payment_information',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='payment_information',
            name='card_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='specialist',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Doctor'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='illness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Illness'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Payment_Information'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.User'),
        ),
        migrations.AddField(
            model_name='doctor_rating',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Doctor'),
        ),
        migrations.AddField(
            model_name='doctor_rating',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Rating'),
        ),
        migrations.AddField(
            model_name='coverage',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Doctor'),
        ),
        migrations.AddField(
            model_name='coverage',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.InsuranceCompany'),
        ),
        migrations.AddField(
            model_name='auction_delivery',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Delivery'),
        ),
    ]
