# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_auto_20170417_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
