# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 18:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root', '0005_auto_20170417_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.BooleanField(default=False)),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Clients')),
                ('illness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Illness')),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_information',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='symptoms',
        ),
        migrations.DeleteModel(
            name='UserCredentials',
        ),
        migrations.AddField(
            model_name='payment_information',
            name='paymentid',
            field=models.AutoField(default=b'1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Clients'),
        ),
        migrations.AlterField(
            model_name='payment_information',
            name='card_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suffersfrom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Clients'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='clients',
            name='diagnoses',
            field=models.ManyToManyField(through='root.Diagnosis', to='root.Illness'),
        ),
        migrations.AddField(
            model_name='clients',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='root.Payment_Information'),
        ),
        migrations.AddField(
            model_name='clients',
            name='shopping_cart',
            field=models.ManyToManyField(through='root.Cart', to='root.Remedy'),
        ),
        migrations.AddField(
            model_name='clients',
            name='symptoms',
            field=models.ManyToManyField(through='root.SuffersFrom', to='root.Symptom'),
        ),
        migrations.AddField(
            model_name='clients',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
